version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: mycommerce-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-mycommerce}"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: mycommerce-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:7
    container_name: mycommerce-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mycommerce-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  graylog:
    image: graylog/graylog:5.0
    container_name: mycommerce-graylog
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      GRAYLOG_PASSWORD_SECRET: "supersecret"
      GRAYLOG_ROOT_PASSWORD_SHA2: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd60f1a82bdf6a6191f" # 'password'
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514"

volumes:
  postgres-data:
  mongodb-data:
  redis-data:
